Vagrant.configure(2) do |config|
  config.ssh.username = "vagrant"
  # config.ssh.password = "sunyafei"
  config.ssh.insert_key = false

  config.vm.synced_folder "./", "/vagrant", disabled: true
  config.vm.synced_folder "~/sun", "/sun", type: "nfs", mount_options: ["nolock", "vers=3", "udp", "noatime", "actimeo=1"]

  config.vm.box = "rails"
  config.vm.network "private_network", ip: "172.28.128.3"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "800"
    vb.cpus = 2
  end
end
