module VagrantPlugins
  module GuestLinux
    class Plugin < Vagrant.plugin("2")
      guest_capability("linux", "change_host_name") { Cap::ChangeHostName }
      guest_capability("linux", "configure_networks") { Cap::ConfigureNetworks }
    end
  end
end

Vagrant.configure(2) do |config|
  config.vm.define "barge"
  config.vm.box = "ailispaw/barge"
  config.vm.network "private_network", ip: "172.28.128.6"
  config.vm.synced_folder ".", "/vagrant", type: "nfs", disabled: true
  config.vm.synced_folder "~/sun", "/sun", type: "nfs", mount_options: ["nolock", "vers=3", "udp", "noatime", "actimeo=1"]

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "500"
    vb.cpus = 2
  end
end